export const postData = [
  {
    name: "John Doe",
    text: "Just had a great time at the beach",
    image: null,
    auto: true,
    id: crypto.randomUUID(),
    impressions: 2,
  },
  {
    name: "Jane Smith",
    text: "I can't believe it's already August!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 10,
  },
  {
    name: "Bob Johnson",
    text: "Anyone up for a game of basketball?",
    image: null,
    auto: true,
    id: crypto.randomUUID(),
    impressions: 2,
  },
  {
    name: "Alice Lee",
    text: "Had a delicious dinner at the new restaurant in town!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 2,
  },
  {
    name: "Tom Wilson",
    text: "Just finished reading a great book!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 2,
  },
  {
    name: "Samantha Brown",
    text: "Excited for my upcoming vacation!",
    image: null,
    auto: true,
    id: crypto.randomUUID(),
    impressions: 5,
  },
  {
    name: "David Kim",
    text: "Can't wait for the new Marvel movie to come out!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 5,
  },
  {
    name: "Emily Chen",
    text: "Had a fun day at the amusement park!",
    image: null,
    auto: true,
    id: crypto.randomUUID(),
    impressions: 5,
  },
  {
    name: "Michael Davis",
    text: "Just got a new job!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 5,
  },
  {
    name: "Olivia Rodriguez",
    text: "Missing my friends from college!",
    image: null,
    id: crypto.randomUUID(),
    impressions: 5,
  },
];
